version: "3.7"

services:
  jenkins:
    build:
      context: .
    container_name: jenkins
    user: jenkins
    volumes:
      - /data/jenkins:/var/jenkins_home
    environment:
      - JENKINS_HOST_HOME: "/data/jenkins"
    ports:
      - "8080:8080"
      - "50000:50000"
    secrets:
     - adminPassword 
secrets:
  adminPassword:
    file: ./secrets/initialAdminPassword
    
    
