version: "3.7"

services:
  jenkins:
    image: jenkins/jenkins:alpine
    container_name: jenkins
    user: jenkins
    volumes:
      - /data/jenkins:/var/jenkins_home
    environment:
      - JENKINS_HOST_HOME: "/data/jenkins"
      - JENKINS_UC  ####
    ports:
      - "8080:8080"
      - "50000:50000"
    secrets:
     - adminPassword
     
secrets:
  adminPassword:
    file: ./secrets/initialAdminPassword
