version: "3.7" 
 
services: 
  jenkins: 
    build: 
      context: . 
    container_name: jenkins 
    user: jenkins 
    volumes: 
      - jenkins_data:/var/jenkins_home 
    ports: 
      - "8080:8080" 
      - "50000:50000" 
 
volumes: 
  jenkins_data: 
    driver: local 
   
